---
output: rmarkdown::github_document
editor_options: 
  chunk_output_type: console
---
```{r pkg-knitr-opts, include=FALSE}
hrbrpkghelpr::global_opts()
```

```{r badges, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::stinking_badges(branch = "master")
```

```{r description, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::yank_title_and_description()
```

## IMPORTANT

This package has been updated to use Wappalyzer v6.10.40.

It is still a major WIP.

You will temporarily need to do your own "joins" for applications, categories and groups via `wap_application()`, `wap_categories()`,  and `wap_groups()`.

## What's Inside The Tin

The following functions are implemented:

```{r ingredients, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::describe_ingredients()
```

## Installation

```{r install-ex, results='asis', echo=FALSE, cache=FALSE}
hrbrpkghelpr::install_block()
```

## Usage

```{r lib-ex}
library(rappalyzer)
library(ragg)
# current version
packageVersion("rappalyzer")
```

```{r some-wapples}
rappalyze("https://rud.is/b") 

rappalyze("https://greynoise.io/blog")

rappalyze("https://docs.rs/") 

rappalyze("https://tailwindcss.com/")

rappalyze("https://example.com")
```

## rappalyzer Metrics

```{r cloc, echo=FALSE}
cloc::cloc_pkg_md()
```
